var nodeoptions = document.querySelector('#countryname_id').querySelectorAll('option');
var infos = "";
for(var index in nodeoptions){
	infos = infos + nodeoptions[index].value + ":" + nodeoptions[index].innerHTML + ","
}
console.log(infos);
性别
M:MALE,F:FEMALE,X:TRANSGENDER
出生国家
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
宗教
BAHAI:BAHAI,BUDDHISM:BUDDHISM,CHRISTIAN:CHRISTIAN,HINDU:HINDU,ISLAM:ISLAM,JAINISM:JAINISM,JUDAISM:JUDAISM,OTHERS:OTHERS,PARSI:PARSI,SIKH:SIKH,ZOROASTRIAN:ZOROASTRIAN
教育状况
BELOW MATRICULATION:BELOW MATRICULATION,GRADUATE:GRADUATE,HIGHER SECONDARY:HIGHER SECONDARY,ILLITERATE:ILLITERATE,MATRICULATION:MATRICULATION,NA BEING MINOR:NA BEING MINOR,OTHERS:OTHERS,POST GRADUATE:POST GRADUATE,PROFESSIONAL:PROFESSIONAL
获得国籍的方式
BY BIRTH:By Birth,NATURALIZATION:Naturalization
其它护照签发国家
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
其它护照国籍
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE

var data={surname:'ZHANG',givenName:'YALAN',changedSurnameCheck:'no',gender:'F',birth_place:'xxx',country_birth:'CHN',nic_number:'410703198208143251',
religion:'OTHERS',religion_other:'NA',identity_marks:'NA',education:'GRADUATE', nationality_by:'BY BIRTH',passport_no:'E12345678',passport_issue_place:'JIANGSU',passport_issue_date:'21/02/2018',
passport_expiry_date:'31/01/2028',other_ppt_1:'no'};
function currentStepFinish(callback){
	window.cefQuery({
		request: 'CurrentStepFinish:',
		onSuccess: function(response) {
			callback();
		},
		onFailure: function(error_code, error_message) {
		}
	});
};
function fillPassportDetails(){
	document.querySelector('#passport_no').value=data.passport_no;
	document.querySelector('#passport_issue_place').value=data.passport_issue_place;
	document.querySelector('#passport_issue_date').value=data.passport_issue_date;
	document.querySelector('#passport_expiry_date').value=data.passport_expiry_date;
	if(data.other_ppt_1.toUpperCase() == 'YES'){
		document.querySelector('#other_ppt_1').click();
		var interval = setInterval(function(){
			if(document.querySelector('#other_ppt_country_issue') != null && document.querySelector('#other_ppt_country_issue').querySelector('option[value=\"'+data.other_ppt_country_issue+'\"]') != null){
				clearInterval(interval);
				document.querySelector('#other_ppt_country_issue').querySelector('option[value=\"'+data.other_ppt_country_issue+'\"]').selected=true;
				document.querySelector('#other_ppt_country_issue').onchange();
				document.querySelector('#other_ppt_no').value=data.other_ppt_no;
				document.querySelector('#other_ppt_issue_date').value=data.other_ppt_issue_date;
				document.querySelector('#other_ppt_issue_place').value=data.other_ppt_issue_place;
				var interval2 = setInterval(function(){
					if(document.querySelector('#other_ppt_nat') != null && document.querySelector('#other_ppt_nat').querySelector('option[value=\"'+data.other_ppt_nat+'\"]') != null){
						clearInterval(interval2);
						document.querySelector('#other_ppt_nat').querySelector('option[value=\"'+data.other_ppt_nat+'\"]').selected=true;
						document.querySelector('#other_ppt_nat').onchange();
						currentStepFinish(function(){
							setTimeout(function(){
								document.querySelector('#continue').click();
							},3000);
						});
					}
				},2000);
			}
		},2000);
	} else {
		document.querySelector('#other_ppt_2').click();
		currentStepFinish(function(){
			setTimeout(function(){
				document.querySelector('#continue').click();
			},3000);
		});
	}
}
function fillAppDetails(){
	document.querySelector('#surname').value=data.surname;
	document.querySelector('#givenName').value=data.givenName;
	if(data.changedSurnameCheck.toUpperCase() == 'YES'){
		document.querySelector('#changedSurnameCheck').click();
		document.querySelector('#prev_surname').value=data.prev_surname;
		document.querySelector('#prev_given_name').value=data.prev_given_name;
	}
	var interval = setInterval(function(){
		if(document.querySelector('#gender') != null && document.querySelector('#gender').querySelector('option[value=\"'+data.gender+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#gender').querySelector('option[value=\"'+data.gender+'\"]').selected=true;
			document.querySelector('#birth_place').value=data.birth_place;
			var country_birthinterval = setInterval(function(){
				if(document.querySelector('#country_birth') != null && document.querySelector('#country_birth').querySelector('option[value=\"'+data.country_birth+'\"]') != null){
					clearInterval(country_birthinterval);
					document.querySelector('#country_birth').querySelector('option[value=\"'+data.country_birth+'\"]').selected=true;
					document.querySelector('#nic_number').value=data.nic_number;
					var religioninterval = setInterval(function(){
						if(document.querySelector('#religion') != null && document.querySelector('#religion').querySelector('option[value=\"'+data.religion+'\"]') != null){
							clearInterval(religioninterval);
							document.querySelector('#religion').querySelector('option[value=\"'+data.religion+'\"]').selected=true;
							document.querySelector('#religion').onchange();
							document.querySelector('#identity_marks').value=data.identity_marks;
							var educationinterval = setInterval(function(){
								if(document.querySelector('#education') != null && document.querySelector('#education').querySelector('option[value=\"'+data.education+'\"]') != null){
									clearInterval(educationinterval);
									if(data.religion=='OTHERS'){
										document.querySelector('#religion_other').value=data.religion_other;
									}
									document.querySelector('#education').querySelector('option[value=\"'+data.education+'\"]').selected=true;
									var nationality_byinterval = setInterval(function(){
										if(document.querySelector('#nationality_by') != null && document.querySelector('#nationality_by').querySelector('option[value=\"'+data.nationality_by+'\"]') != null){
											clearInterval(nationality_byinterval);
											document.querySelector('#nationality_by').querySelector('option[value=\"'+data.nationality_by+'\"]').selected=true;
											document.querySelector('#nationality_by').onchange();
											fillPassportDetails();
										}
									},2000);
								}
							},2000);
						}
					},2000);
				}
			},2000);
		}
	},2000);
}
var interval = setInterval(function(){
	if(document.querySelector('#other_ppt_nat') != null){
		clearInterval(interval);
		fillAppDetails();
	}
},2000);