var nodeoptions = document.querySelector('#countryname_id').querySelectorAll('option');
var infos = "";
for(var index in nodeoptions){
	infos = infos + nodeoptions[index].value + ":" + nodeoptions[index].innerHTML + ","
}

地址国家
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
电话号码国家代码
Other:Other,93:93 - AFGHANISTAN,358:358 - ALAND ISLANDS,355:355 - ALBANIA,213:213 - ALGERIA,684:684 - AMERICAN SAMOA,376:376 - ANDORRA,244:244 - ANGOLA,672:672 - ANTARTICA,268:268 - ANTIGUA AND BARBUDA,54:54 - ARGENTINA,374:374 - ARMENIA,297:297 - ARUBA,61:61 - AUSTRALIA,43:43 - AUSTRIA,994:994 - AZERBAIJAN,973:973 - BAHRAIN,880:880 - BANGLADESH,375:375 - BELARUS,32:32 - BELGIUM,501:501 - BELIZE,229:229 - BENIN,975:975 - BHUTAN,591:591 - BOLIVIA,387:387 - BOSNIA AND HERZEGOVINA,267:267 - BOTSWANA,55:55 - BOUVET ISLAND,55:55 - BRAZIL,246:246 - BRITISH INDIAN OCEAN TERRITORY,673:673 - BRUNEI,359:359 - BULGARIA,226:226 - BURKINA FASO,257:257 - BURUNDI,855:855 - CAMBODIA,237:237 - CAMEROON,1:1 - CANADA,238:238 - CAPE VERDE,1345:1345 - CAYMAN ISLANDS,236:236 - CENTRAL AFRICAN REPUBLIC,235:235 - CHAD,56:56 - CHILE,86:86 - CHINA-CHINA,852:852 - CHINA- SAR HONGKONG,61:61 - CHRISTMAS ISLANDS,891:891 - COCOS (KEELING) ISLANDS,57:57 - COLOMBIA,269:269 - COMOROS,242:242 - CONGO (DEMOCRATIC REPUBLIC OF),682:682 - COOK ISLANDS,506:506 - COSTA RICA,225:225 - COTE D'IVOIRE,385:385 - CROATIA,53:53 - CUBA,850:850 - DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,670:670 - EAST TIMOR (DEMOCRATIC REPUBLIC OF),291:291 - ERITREA,372:372 - ESTONIA,251:251 - ETHIOPIA,500:500 - FALKLAND ISLANDS (MALVINES),298:298 - FAROE ISLANDS,679:679 - FIJI,358:358 - FINLAND,33:33 - FRANCE,33:33 - FRANCE METROPOLITAN,594:594 - FRENCH GUIANA,689:689 - FRENCH POLYNESIA,262:262 - FRENCH SOUTHERN TERRITORIES,241:241 - GABON,220:220 - GAMBIA,995:995 - GEORGIA,49:49 - GERMANY,233:233 - GHANA,350:350 - GIBRALTAR,30:30 - GREECE,299:299 - GREENLAND,590:590 - GUADELOUPE,671:671 - GUAM,502:502 - GUATEMALA,224:224 - GUINEA,245:245 - GUINEA-BISSAU,592:592 - GUYANA,509:509 - HAITI,6723:6723 - HEARD AND MCDONALD ISLANDS,504:504 - HONDURAS,36:36 - HUNGARY,354:354 - ICELAND,91:91 - INDIA,62:62 - INDONESIA,98:98 - IRAN,964:964 - IRAQ,353:353 - IRELAND,972:972 - ISRAEL,39:39 - ITALY,81:81 - JAPAN,962:962 - JORDAN,7:7 - KAZAKHSTAN,254:254 - KENYA,686:686 - KIRIBATI,965:965 - KUWAIT,996:996 - KYRGYZSTAN,856:856 - LAOS,371:371 - LATVIA,218:218 - LIBYA,352:352 - LUXEMBOURG,223:223 - MALI,356:356 - MALTA,692:692 - MARSHALL ISLANDS,596:596 - MARTINIQUE,222:222 - MAURITANIA,230:230 - MAURITIUS,262:262 - MAYOTTE,52:52 - MEXICO,262:262 - MICRONESIA (FEDERATED STATES OF),373:373 - MOLDOVA,976:976 - MONGOLIA,382:382 - MONTENEGRO,664:664 - MONTSERRAT,212:212 - MOROCCO,258:258 - MOZAMBIQUE,95:95 - MYANMAR,264:264 - NAMIBIA,674:674 - NAURU,977:977 - NEPAL,31:31 - NETHERLANDS,599:599 - NETHERLANDS ANTILLES,687:687 - NEW CALEDONIA,64:64 - NEW ZEALAND,505:505 - NICARAGUA,227:227 - NIGER,234:234 - NIGERIA,683:683 - NIUE ISLAND,672:672 - NORFOLK ISLAND,1670:1670 - NORTHERN MARIANA ISLANDS,47:47 - NORWAY,968:968 - OMAN,92:92 - PAKISTAN,680:680 - PALAU,970:970 - PALESTINE,507:507 - PANAMA,675:675 - PAPUA NEW GUINEA,595:595 - PARAGUAY,51:51 - PERU,63:63 - PHILIPPINES,64:64 - PITCAIRN,48:48 - POLAND,351:351 - PORTUGAL,974:974 - QATAR,82:82 - REPUBLIC OF KOREA,389:389 - REPUBLIC OF MACEDONIA,383:383 - RESIDENT OF KOSOVO (UNMIK),262:262 - REUNION,40:40 - ROMANIA,7:7 - RUSSIAN FEDERATION,250:250 - RWANDA,290:290 - SAINT HELENA,1758:1758 - SAINT LUCIA,508:508 - SAINT PIERRE AND MIQUELON,1784:1784 - SAINT VINCENT AND THE GRENADINES,1684:1684 - SAMOA,378:378 - SAN MARINO,239:239 - SAO TOME AND PRINCIPE,966:966 - SAUDI ARABIA,221:221 - SENEGAL,381:381 - SERBIA,248:248 - SEYCHELLES,232:232 - SIERRA LEONE,65:65 - SINGAPORE,421:421 - SLOVAKIA,386:386 - SLOVENIA,677:677 - SOLOMON ISLANDS,252:252 - SOMALIA,27:27 - SOUTH AFRICA,500:500 - SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,211:211 - SOUTH SUDAN,34:34 - SPAIN,94:94 - SRI LANKA,249:249 - SUDAN,597:597 - SURINAME,47:47 - SVALBARD AND JAN MAYEN ISLANDS,268:268 - SWAZILAND,46:46 - SWEDEN,41:41 - SWITZERLAND,963:963 - SYRIAN ARAB REPUBLIC,886:886 - TAIWAN,992:992 - TAJIKISTAN,255:255 - TANZANIA,66:66 - THAILAND,228:228 - TOGO,690:690 - TOKELAU,676:676 - TONGA,1868:1868 - TRINIDAD AND TOBAGO,216:216 - TUNISIA,90:90 - TURKEY,993:993 - TURKMENISTAN,688:688 - TUVALU,256:256 - UGANDA,380:380 - UKRAINE,971:971 - UNITED ARAB EMIRATES,44:44 - UNITED KINGDOM,1:1 - UNITED STATES OF AMERICA,598:598 - URUGUAY,7:7 - UZBEKISTAN,678:678 - VANUATU,379:379 - VATICAN CITY STATE ( HOLY SEE),58:58 - VENEZUELA,84:84 - VIETNAM,1284:1284 - VIRGIN ISLANDS (BRITISH),1340:1340 - VIRGIN ISLANDS (US),681:681 - WALLIS AND FUTUNA ISLANDS,212:212 - WESTERN SAHARA,969:969 - YEMEN,381:381 - YUGOSLAVIA,260:260 - ZAMBIA,263:263 - ZIMBABWE
国籍
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
出生国家
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
婚姻状态
0:MARRIED,1:SINGLE
当前职业
AIR FORCE:AIR FORCE,BUSINESS PERSON:BUSINESS PERSON,CAMERAMAN:CAMERAMAN,CHARITY/SOCIAL WORKER:CHARITY/SOCIAL WORKER,CHARTERED ACCOUNTANT:CHARTERED ACCOUNTANT,COLLEGE/UNIVERSITY TEACHER:COLLEGE/UNIVERSITY TEACHER,DIPLOMAT:DIPLOMAT,DOCTOR:DOCTOR,ENGINEER:ENGINEER,FILM PRODUCER:FILM PRODUCER,GOVERNMENT SERVICE:GOVERNMENT SERVICE,HOUSE WIFE:HOUSE WIFE,JOURNALIST:JOURNALIST,LABOUR:LABOUR,LAWYER:LAWYER,MEDIA:MEDIA,MILITARY:MILITARY,MISSIONARY:MISSIONARY,NAVY:NAVY,NEWS BROADCASTER:NEWS BROADCASTER,OFFICIAL:OFFICIAL,OTHERS:OTHERS,POLICE:POLICE,PRESS:PRESS,PRIVATE SERVICE:PRIVATE SERVICE,PUBLISHER:PUBLISHER,REPORTER:REPORTER,RESEARCHER:RESEARCHER,RETIRED:RETIRED,SEA MAN:SEA MAN,SELF EMPLOYED/ FREELANCER:SELF EMPLOYED/ FREELANCER,STUDENT:STUDENT,TRADER:TRADER,TV PRODUCER:TV PRODUCER,UN-EMPLOYED:UN-EMPLOYED,UN OFFICIAL:UN OFFICIAL,WORKER:WORKER,WRITER:WRITER

var data = {pres_add1:'xxx',pres_add2:'SHANGHAI',pres_country:'CHN',pres_add3:'xxxx',pincode:'453000',pres_phone:'18601615518',isd_code1:'86',mobile:'18601615518',
perm_address1:'xxx',perm_address2:'xxx',perm_address3:'xxx',fthrname:'LIDS',father_nationality:'CHN',father_previous_nationality:'CHN',
father_place_of_birth:'JIANGSU',father_country_of_birth:'CHN',mother_name:'XXX',mother_nationality:'CHN',mother_previous_nationality:'CHN',mother_place_of_birth:'JIANGSU',
mother_country_of_birth:'CHN',marital_status:'1',occupation:'BUSINESS PERSON',empname:'xxx',empdesignation:'xxx',empaddress:'xxx',empphone:'18601615518',
previous_occupation:'BUSINESS PERSON',prev_org1:'no',previous_occupation:'',sameAddress_id:'yes'};
function currentStepFinish(callback){
	window.cefQuery({
		request: 'CurrentStepFinish:',
		onSuccess: function(response) {
			callback();
		},
		onFailure: function(error_code, error_message) {
		}
	});
};
function fillOccupationInfo(){
	var interval = setInterval(function(){
		if(document.querySelector('#occupation') != null && document.querySelector('#occupation').querySelector('option[value=\"'+data.occupation+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#occupation').querySelector('option[value=\"'+data.occupation+'\"]').selected=true;
			document.querySelector('#occupation').onchange();
			setTimeout(function(){
				document.querySelector('#empname').value=data.empname;
				document.querySelector('#empdesignation').value=data.empdesignation;
				document.querySelector('#empaddress').value=data.empaddress;
				document.querySelector('#empphone').value=data.empphone;
				if(data.previous_occupation == '') {
					if(data.prev_org1.toUpperCase() == 'YES') {
						document.querySelector('#prev_org1').click();
						document.querySelector('#previous_organization').value=data.previous_organization;
						document.querySelector('#previous_designation').value=data.previous_designation;
						document.querySelector('#previous_rank').value=data.previous_rank;
						document.querySelector('#previous_posting').value=data.previous_posting;
					} else {
						document.querySelector('#prev_org2').click();
					}
					setTimeout(function(){
						currentStepFinish(function(){document.querySelector('#continue').click();});
					}, 3000);
				} else {
					var previous_occupationInterval = setInterval(function(){
						if(document.querySelector('#previous_occupation') != null && document.querySelector('#previous_occupation').querySelector('option[value=\"'+data.previous_occupation+'\"]') != null){
							clearInterval(interval);
							document.querySelector('#previous_occupation').querySelector('option[value=\"'+data.previous_occupation+'\"]').selected=true;
							document.querySelector('#previous_occupation').onchange();
							if(data.prev_org1.toUpperCase() == 'YES') {
								document.querySelector('#prev_org1').click();
								document.querySelector('#previous_organization').value=data.previous_organization;
								document.querySelector('#previous_designation').value=data.previous_designation;
								document.querySelector('#previous_rank').value=data.previous_rank;
								document.querySelector('#previous_posting').value=data.previous_posting;
							} else {
								document.querySelector('#prev_org2').click();
							}
							setTimeout(function(){
								currentStepFinish(function(){document.querySelector('#continue').click();});
							}, 3000);
						}
					}, 3000);
				}
			}, 2000);
		}
	},2000);
}
function fillSpouseInfo(){
	document.querySelector('#spouse_name').value=data.spouse_name;
	var interval = setInterval(function(){
		if(document.querySelector('#spouse_nationality') != null && document.querySelector('#spouse_nationality').querySelector('option[value=\"'+data.spouse_nationality+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#spouse_nationality').querySelector('option[value=\"'+data.spouse_nationality+'\"]').selected=true;
			document.querySelector('#spouse_nationality').onchange();
			var preInterval = setInterval(function(){
				if(document.querySelector('#spouse_previous_nationality') != null && document.querySelector('#spouse_previous_nationality').querySelector('option[value=\"'+data.spouse_previous_nationality+'\"]') != null){
					clearInterval(interval);
					document.querySelector('#spouse_previous_nationality').querySelector('option[value=\"'+data.spouse_previous_nationality+'\"]').selected=true;
					document.querySelector('#spouse_previous_nationality').onchange();
					document.querySelector('#spouse_place_of_birth').value=data.spouse_place_of_birth;
					var birthInterval = setInterval(function(){
						if(document.querySelector('#spouse_country_of_birth') != null && document.querySelector('#spouse_country_of_birth').querySelector('option[value=\"'+data.spouse_country_of_birth+'\"]') != null){
							clearInterval(interval);
							document.querySelector('#spouse_country_of_birth').querySelector('option[value=\"'+data.spouse_country_of_birth+'\"]').selected=true;
							document.querySelector('#spouse_country_of_birth').onchange();
							setTimeout(function(){
								fillOccupationInfo();
							}, 3000);
						}
					}, 2000);
				}
			},2000);
		}
	},2000);
}
function fillMotherDetails(){
	document.querySelector('#mother_name').value=data.mother_name;
	var interval = setInterval(function(){
		if(document.querySelector('#mother_nationality') != null && document.querySelector('#mother_nationality').querySelector('option[value=\"'+data.mother_nationality+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#mother_nationality').querySelector('option[value=\"'+data.mother_nationality+'\"]').selected=true;
			var preInterval = setInterval(function(){
				if(document.querySelector('#mother_previous_nationality') != null && document.querySelector('#mother_previous_nationality').querySelector('option[value=\"'+data.mother_previous_nationality+'\"]') != null){
					clearInterval(interval);
					document.querySelector('#mother_previous_nationality').querySelector('option[value=\"'+data.mother_previous_nationality+'\"]').selected=true;
					document.querySelector('#mother_place_of_birth').value=data.mother_place_of_birth;
					var birthInterval = setInterval(function(){
						if(document.querySelector('#mother_country_of_birth') != null && document.querySelector('#mother_country_of_birth').querySelector('option[value=\"'+data.mother_country_of_birth+'\"]') != null){
							clearInterval(interval);
							document.querySelector('#mother_country_of_birth').querySelector('option[value=\"'+data.mother_country_of_birth+'\"]').selected=true;
							var birthInterval = setInterval(function(){
								if(document.querySelector('#marital_status') != null && document.querySelector('#marital_status').querySelector('option[value=\"'+data.marital_status+'\"]') != null){
									clearInterval(interval);
									document.querySelector('#marital_status').querySelector('option[value=\"'+data.marital_status+'\"]').selected=true;
									document.querySelector('#grandparent_flag2').click();
									if(data.marital_status == '0'){
										fillSpouseInfo();
									} else {
										setTimeout(function(){
											fillOccupationInfo();
										}, 3000);
									}
								}
							}, 2000);
						}
					}, 2000);
				}
			},2000);
		}
	},2000);
}
function fillFatherDetails(){
	document.querySelector('#fthrname').value=data.fthrname;
	var interval = setInterval(function(){
		if(document.querySelector('#father_nationality') != null && document.querySelector('#father_nationality').querySelector('option[value=\"'+data.father_nationality+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#father_nationality').querySelector('option[value=\"'+data.father_nationality+'\"]').selected=true;
			var preInterval = setInterval(function(){
				if(document.querySelector('#father_previous_nationality') != null && document.querySelector('#father_previous_nationality').querySelector('option[value=\"'+data.father_previous_nationality+'\"]') != null){
					clearInterval(interval);
					document.querySelector('#father_previous_nationality').querySelector('option[value=\"'+data.father_previous_nationality+'\"]').selected=true;
					document.querySelector('#father_place_of_birth').value=data.father_place_of_birth;
					var birthInterval = setInterval(function(){
						if(document.querySelector('#father_country_of_birth') != null && document.querySelector('#father_country_of_birth').querySelector('option[value=\"'+data.father_country_of_birth+'\"]') != null){
							clearInterval(interval);
							document.querySelector('#father_country_of_birth').querySelector('option[value=\"'+data.father_country_of_birth+'\"]').selected=true;
							fillMotherDetails();
						}
					}, 2000);
				}
			},2000);
		}
	},2000);
}
function fillAddDetails(){
	document.querySelector('#pres_add1').value=data.pres_add1;
	document.querySelector('#pres_add2').value=data.pres_add2;
	var interval = setInterval(function(){
		if(document.querySelector('#pres_country') != null && document.querySelector('#pres_country').querySelector('option[value=\"'+data.pres_country+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#pres_country').querySelector('option[value=\"'+data.pres_country+'\"]').selected=true;
			document.querySelector('#pres_country').onchange();
			document.querySelector('#pres_add3').value=data.pres_add3;
			document.querySelector('#pincode').value=data.pincode;
			document.querySelector('#pres_phone').value=data.pres_phone;
			var phoneCodeInterval = setInterval(function(){
				if(document.querySelector('#isd_code1') != null && document.querySelector('#isd_code1').querySelector('option[value=\"'+data.isd_code1+'\"]') != null){
					clearInterval(phoneCodeInterval);
					document.querySelector('#isd_code1').querySelector('option[value=\"'+data.isd_code1+'\"]').selected=true;
					document.querySelector('#isd_code1').onchange();
					setTimeout(function(){
						if(data.isd_code1.toUpperCase() == 'OTHER'){
							document.querySelector('#isd_code2').value=data.isd_code2;
						}
						document.querySelector('#mobile').value=data.mobile;
						if(data.sameAddress_id.toUpperCase() == 'YES'){
							document.querySelector('#sameAddress_id').click();
						} else {
							document.querySelector('#perm_address1').value=data.perm_address1;
							document.querySelector('#perm_address2').value=data.perm_address2;
							document.querySelector('#perm_address3').value=data.perm_address3;
						}
						setTimeout(function(){
							fillFatherDetails();
						},3000);
					}, 3000);
				}
			}, 2000);
		}
	},2000);
}
var interval = setInterval(function(){
	if(document.querySelector('#previous_posting') != null){
		clearInterval(interval);
		fillAddDetails();
	}
},2000);