var nodeoptions = document.querySelector('#countryname_id').querySelectorAll('option');
var infos = "";
for(var index in nodeoptions){
	infos = infos + nodeoptions[index].value + ":" + nodeoptions[index].innerHTML + ","
}
console.log(infos);
申请签证人所在国家
AFG:AFGHANISTAN,DZA:ALGERIA,AGO:ANGOLA,ARG:ARGENTINA,ARM:ARMENIA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHR:BAHRAIN,BLR:BELARUS,BEL:BELGIUM,BWA:BOTSWANA,BRA:BRAZIL,BRN:BRUNEI,BGR:BULGARIA,KHM:CAMBODIA,CAN:CANADA,CHL:CHILE,CHN:CHINA-CHINA,COL:COLOMBIA,CIV:COTE D\'IVOIRE,HRV:CROATIA,CUB:CUBA,CZE:CZECH REPUBLIC,DNK:DENMARK,EGY:EGYPT,ETH:ETHIOPIA,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,DEU:GERMANY,GHA:GHANA,GRC:GREECE,GTM:GUATEMALA,HUN:HUNGARY,ISL:ICELAND,IND:INDIA,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,MDG:MADAGASCAR,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MUS:MAURITIUS,MEX:MEXICO,MNG:MONGOLIA,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NPL:NEPAL,NLD:NETHERLANDS,NZL:NEW ZEALAND,NER:NIGER,NGA:NIGERIA,NOR:NORWAY,OMN:OMAN,PAK:PAKISTAN,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PER:PERU,PHL:PHILIPPINES,POL:POLAND,PRT:PORTUGAL,QAT:QATAR,KOR:REPUBLIC OF KOREA,REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,ZAF:SOUTH AFRICA,SSD:SOUTH SUDAN,ESP:SPAIN,LKA:SRI LANKA,SDN:SUDAN,SUR:SURINAME,SWE:SWEDEN,CHE:SWITZERLAND,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,UGA:UGANDA,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,USA:UNITED STATES OF AMERICA,UZB:UZBEKISTAN,VEN:VENEZUELA,VNM:VIETNAM,YEM:YEMEN,ZMB:ZAMBIA,ZWE:ZIMBABWE
申请人城市
CHNB:CHINA-BEIJING,CHNG:CHINA - GUANGZHOU,CHNH:CHINA-HONG KONG,CHNS:CHINA-SHANGHAI
申请人国籍
AFG:AFGHANISTAN,ALA:ALAND ISLANDS,ALB:ALBANIA,DZA:ALGERIA,ASM:AMERICAN SAMOA,AND:ANDORRA,AGO:ANGOLA,AIA:ANGUILLA,ATA:ANTARTICA,ATG:ANTIGUA AND BARBUDA,ARG:ARGENTINA,ARM:ARMENIA,ABW:ARUBA,AUS:AUSTRALIA,AUT:AUSTRIA,AZE:AZERBAIJAN,BHS:BAHAMAS,BHR:BAHRAIN,BGD:BANGLADESH,BRB:BARBADOS,BLR:BELARUS,BEL:BELGIUM,BLZ:BELIZE,BEN:BENIN,BMU:BERMUDA,BTN:BHUTAN,BOL:BOLIVIA,BIH:BOSNIA AND HERZEGOVINA,BWA:BOTSWANA,BVT:BOUVET ISLAND,BRA:BRAZIL,IOT:BRITISH INDIAN OCEAN TERRITORY,BRN:BRUNEI,BGR:BULGARIA,BFA:BURKINA FASO,BDI:BURUNDI,KHM:CAMBODIA,CMR:CAMEROON,CAN:CANADA,CPV:CAPE VERDE,XCC:CARRIBEAN COMMUNITY,CYM:CAYMAN ISLANDS,CAF:CENTRAL AFRICAN REPUBLIC,TCD:CHAD,CHL:CHILE,CHN:CHINA-CHINA,HKG:CHINA- SAR HONGKONG,MAC:CHINA- SAR MACAU,CXR:CHRISTMAS ISLANDS,CCK:COCOS (KEELING) ISLANDS,COL:COLOMBIA,COM:COMOROS,COG:CONGO,COD:CONGO (DEMOCRATIC REPUBLIC OF),COK:COOK ISLANDS,CRI:COSTA RICA,CIV:COTE D'IVOIRE,HRV:CROATIA,CUB:CUBA,CYP:CYPRUS,CZE:CZECH REPUBLIC,PRK:DEMOCRATIC PEOPLE'S REPUBLIC OF KOREA,DNK:DENMARK,DJI:DJIBOUTI,DMA:DOMINICA,DOM:DOMINICAN REPUBLIC,TLS:EAST TIMOR (DEMOCRATIC REPUBLIC OF),ECU:ECUADOR,EGY:EGYPT,SLV:EL SALVADOR,GNQ:EQUATORIAL GUINEA,ERI:ERITREA,EST:ESTONIA,ETH:ETHIOPIA,FLK:FALKLAND ISLANDS (MALVINES),FRO:FAROE ISLANDS,FJI:FIJI,FIN:FINLAND,FRA:FRANCE,FXX:FRANCE METROPOLITAN,GUF:FRENCH GUIANA,PYF:FRENCH POLYNESIA,ATF:FRENCH SOUTHERN TERRITORIES,GAB:GABON,GMB:GAMBIA,GEO:GEORGIA,DEU:GERMANY,GHA:GHANA,GIB:GIBRALTAR,GRC:GREECE,GRL:GREENLAND,GRD:GRENADA,GLP:GUADELOUPE,GUM:GUAM,GTM:GUATEMALA,GGY:GUERNSEY,GIN:GUINEA,GNB:GUINEA-BISSAU,GUY:GUYANA,HTI:HAITI,HMD:HEARD AND MCDONALD ISLANDS,HND:HONDURAS,HUN:HUNGARY,ISL:ICELAND,IDN:INDONESIA,IRN:IRAN,IRQ:IRAQ,IRL:IRELAND,IMN:ISLE OF MAN,ISR:ISRAEL,ITA:ITALY,JAM:JAMAICA,JPN:JAPAN,JEY:JERSEY,JOR:JORDAN,KAZ:KAZAKHSTAN,KEN:KENYA,KIR:KIRIBATI,KWT:KUWAIT,KGZ:KYRGYZSTAN,LAO:LAOS,LVA:LATVIA,LBN:LEBANON,LSO:LESOTHO,LBR:LIBERIA,LBY:LIBYA,LIE:LIECHTENSTEIN,LTU:LITHUANIA,LUX:LUXEMBOURG,MDG:MADAGASCAR,MWI:MALAWI,MYS:MALAYSIA,MDV:MALDIVES,MLI:MALI,MLT:MALTA,MHL:MARSHALL ISLANDS,MTQ:MARTINIQUE,MRT:MAURITANIA,MUS:MAURITIUS,MYT:MAYOTTE,MEX:MEXICO,FSM:MICRONESIA (FEDERATED STATES OF),MDA:MOLDOVA,MCO:MONACO,MNG:MONGOLIA,MNE:MONTENEGRO,MSR:MONTSERRAT,MAR:MOROCCO,MOZ:MOZAMBIQUE,MMR:MYANMAR,NAM:NAMIBIA,NRU:NAURU,NPL:NEPAL,NLD:NETHERLANDS,ANT:NETHERLANDS ANTILLES,NTZ:NEUTRAL ZONE,NCL:NEW CALEDONIA,NZL:NEW ZEALAND,NIC:NICARAGUA,NER:NIGER,NGA:NIGERIA,NIU:NIUE ISLAND,NFK:NORFOLK ISLAND,MNP:NORTHERN MARIANA ISLANDS,NOR:NORWAY,OMN:OMAN,OTH:OTHERS,PAK:PAKISTAN,PLW:PALAU,PSE:PALESTINE,PAN:PANAMA,PNG:PAPUA NEW GUINEA,PRY:PARAGUAY,XXX:PERSON OF UNSPECIFIED NATIONALITY,PER:PERU,PHL:PHILIPPINES,PCN:PITCAIRN,POL:POLAND,PRT:PORTUGAL,PRI:PUERTO RICO,QAT:QATAR,XXB:REFUGEE,XXC:REFUGEE(NON-CONVENTIONAL),KOR:REPUBLIC OF KOREA,MKD:REPUBLIC OF MACEDONIA,UNK:RESIDENT OF KOSOVO (UNMIK),REU:REUNION,ROU:ROMANIA,RUS:RUSSIAN FEDERATION,RWA:RWANDA,SHN:SAINT HELENA,KNA:SAINT KITTS AND NEVIS,LCA:SAINT LUCIA,SPM:SAINT PIERRE AND MIQUELON,VCT:SAINT VINCENT AND THE GRENADINES,WSM:SAMOA,SMR:SAN MARINO,STP:SAO TOME AND PRINCIPE,SAU:SAUDI ARABIA,SEN:SENEGAL,SRB:SERBIA,SYC:SEYCHELLES,SLE:SIERRA LEONE,SGP:SINGAPORE,SVK:SLOVAKIA,SVN:SLOVENIA,SLB:SOLOMON ISLANDS,SOM:SOMALIA,ZAF:SOUTH AFRICA,SGS:SOUTH GEORGIA AND SOUTH SANDWICH ISLANDS,SSD:SOUTH SUDAN,XOM:SOVEREIGN MILITARY ORDER OF MALTA,ESP:SPAIN,LKA:SRI LANKA,XXA:STATELESS,SDN:SUDAN,SUR:SURINAME,SJM:SVALBARD AND JAN MAYEN ISLANDS,SWZ:SWAZILAND,SWE:SWEDEN,CHE:SWITZERLAND,SYR:SYRIAN ARAB REPUBLIC,TWN:TAIWAN,TJK:TAJIKISTAN,TZA:TANZANIA,THA:THAILAND,TBT:TIBET,TGO:TOGO,TKL:TOKELAU,TON:TONGA,TTO:TRINIDAD AND TOBAGO,TUN:TUNISIA,TUR:TURKEY,TKM:TURKMENISTAN,TCA:TURKS AND CAICOS ISL,TUV:TUVALU,UGA:UGANDA,GBD:UK BRITISH DEPENDENT TERRITORIES CITIZEN,GBN:UK BRITISH NATIONAL(OVERSEES),GBO:UK BRITISH OVERSEES CITIZEN,GBP:UK BRITISH PROTECTED PERSON,GBS:UK BRITISH SUBJECT,UKR:UKRAINE,ARE:UNITED ARAB EMIRATES,GBR:UNITED KINGDOM,UNO:UNITED NATIONS ORGANIZATION,UNA:UNITED NATIONS SPECIALIZED AGENCY,UMI:UNITED STATES MINOR OUTLYING ISLANDS,USA:UNITED STATES OF AMERICA,URY:URUGUAY,UZB:UZBEKISTAN,VUT:VANUATU,VAT:VATICAN CITY STATE ( HOLY SEE),VEN:VENEZUELA,VNM:VIETNAM,VGB:VIRGIN ISLANDS (BRITISH),VIR:VIRGIN ISLANDS (US),WLF:WALLIS AND FUTUNA ISLANDS,ESH:WESTERN SAHARA,YEM:YEMEN,YUG:YUGOSLAVIA,ZMB:ZAMBIA,ZWE:ZIMBABWE
签证类型
1:BUSINESS VISA,4:CONFERENCE VISA,11:DIPLOMATIC VISA,9:EMPLOYMENT  VISA,6:ENTRY VISA,84:FILM VISA,85:INTERN VISA,8:JOURNALIST VISA,13:MEDICAL ATTENDANT,16:MEDICAL VISA,7:MISSIONARY VISA,63:MOUNTAINEERING VISA,12:OFFICIAL VISA,65:PROJECT VISA,66:RESEARCH VISA,2:STUDENT VISA,3:TOURIST VISA,5:TRANSIT VISA,86:UN DIPLOMAT,17:UN OFFICIAL
目的
101:SHORT TERM BUSINESS, TECHNICAL MEETINGS,102:BUSINESS VISIT FOR SMALL AND MEDIUM BUSINESS,103:BUSINESS VISIT FOR LARGE BUSINESS,104:BUSINESS VISIT FOR INVESTORS,105:DEPENDENT OF BUSINESS PERSON(SHORT TERM BUSINESS, TECHNICAL MEETINGS),106:DEPENDENT OF BUSINESS PERSON(BUSINESS VISIT FOR SMALL AND MEDIUM BUSINESS),107:DEPENDENT OF BUSINESS PERSON(BUSINESS VISIT FOR LARGE BUSINESS),108:DEPENDENT OF BUSINESS PERSON(BUSINESS VISIT FOR INVESTORS)

function currentStepFinish(callback){
	window.cefQuery({
		request: 'CurrentStepFinish:',
		onSuccess: function(response) {
			callback();
		},
		onFailure: function(error_code, error_message) {
		}
	});
};
var data = {countryname_id:'CHN',missioncode_id:'CHNS',nationality_id:'CHN',dob_id:'14/08/1988',email_id:'test@qq.com',email_re_id:'test@qq.com',jouryney_id:'10/04/2018',
visaService:'1',purpose:'101'};
function fillIdentifyCode(){
	window.cefQuery({
		request: 'GetIndianCode:',
		onSuccess: function(response) {
			document.querySelector('#captcha').value=response;
			currentStepFinish(function(){
				setTimeout(function(){
					document.querySelector('input[type=\"submit\"]').click();
				}, 10000);
			});
		},
		onFailure: function(error_code, error_message) {
			currentStepFinish(function(){
				setTimeout(function(){
					document.querySelector('input[type=\"submit\"]').click();
				}, 10000);
			});
		}
	});
}
function fillBaseInfo(){
	document.querySelector('#dob_id').value=data.dob_id;
	document.querySelector('#email_id').value=data.email_id;
	document.querySelector('#email_re_id').value=data.email_re_id;
	document.querySelector('#jouryney_id').value=data.jouryney_id;
	var visaServiceInterval = setInterval(function(){
		if(document.querySelector('#visaService') != null && document.querySelector('#visaService').querySelector('option[value=\"'+data.visaService+'\"]') != null){
			clearInterval(visaServiceInterval);
			document.querySelector('#visaService').querySelector('option[value=\"'+data.visaService+'\"]').selected=true;
			document.querySelector('#visaService').onchange();
			var purposeInterval = setInterval(function(){
				if(document.querySelector('#purpose') != null && document.querySelector('#purpose').querySelector('option[value=\"'+data.purpose+'\"]') != null){
					clearInterval(purposeInterval);
					document.querySelector('#purpose').querySelector('option[value=\"'+data.purpose+'\"]').selected=true;
					fillIdentifyCode();
				}
			});
		}
	});
}
function fillThreeSelectInfo(){
	var interval = setInterval(function(){
		if(document.querySelector('#countryname_id') != null && document.querySelector('#countryname_id').querySelector('option[value=\"'+data.countryname_id+'\"]') != null){
			clearInterval(interval);
			document.querySelector('#countryname_id').querySelector('option[value=\"'+data.countryname_id+'\"]').selected=true;
			document.querySelector('#countryname_id').onchange();
			var cityInterval = setInterval(function(){
				if(document.querySelector('#missioncode_id') != null && document.querySelector('#missioncode_id').querySelector('option[value=\"'+data.missioncode_id+'\"]') != null){
					clearInterval(cityInterval);
					document.querySelector('#missioncode_id').querySelector('option[value=\"'+data.missioncode_id+'\"]').selected=true;
					document.querySelector('#missioncode_id').onchange();
					var nationalityInterval = setInterval(function(){
						if(document.querySelector('#nationality_id') != null && document.querySelector('#nationality_id').querySelector('option[value=\"'+data.nationality_id+'\"]') != null){
							clearInterval(nationalityInterval);
							document.querySelector('#nationality_id').querySelector('option[value=\"'+data.nationality_id+'\"]').selected=true;
							document.querySelector('#nationality_id').onchange();
							setTimeout(function(){fillBaseInfo()},3000);
						}
					}, 2000);
				}
			}, 2000);
		}
	},2000);
}
var interval = setInterval(function(){
	if(document.querySelector('#captcha') != null){
		clearInterval(interval);
		fillThreeSelectInfo();
	}
},2000);